title: Can Jin
description: Can Jin's Personal Website.
author: Can Jin
avatar: /white_photo.JPG
email: jincan333@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: JarvisJinCan
  card: summary
logo: /white_photo.JPG
social:
  name: Can Jin
  links:
    - https://twitter.com/JarvisJinCan
    - https://www.facebook.com/ngzhio
    - https://github.com/jincan333
    - https://https://www.linkedin.com/in/can-jin-a05573274/
    - https://scholar.google.com/citations?user=RK-8dz0AAAAJ&hl=en
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
